language: node_js
sudo: false
node_js:
  - "8"
  - "9"
  - "10"
before_install:
  - export PATH=$HOME/.deno/bin:$PATH
install:
  - curl -L https://deno.land/x/install/install.sh | sh -s v0.3.0
  - yarn
script:
  - take test
after_success: take test:coverage
